# Generated by Django 3.2.4 on 2021-06-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='parametry',
        ),
        migrations.DeleteModel(
            name='ParamProc',
        ),
    ]
