# Generated by Django 3.2.4 on 2021-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0002_auto_20210623_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='opis2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='opis3',
            field=models.TextField(blank=True),
        ),
    ]
