# Generated by Django 3.2.4 on 2021-06-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0003_auto_20210628_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='opis2',
            new_name='opis3_nxt',
        ),
        migrations.RenameField(
            model_name='produkty',
            old_name='opis3',
            new_name='opis_wst',
        ),
    ]
