# Generated by Django 3.2.4 on 2021-06-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_auto_20210628_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamRodz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=90)),
                ('rodzaj_parametrow1', models.TextField(blank=True)),
                ('rodzaj_parametrow2', models.TextField(blank=True)),
                ('rodzaj_parametrow3', models.TextField(blank=True)),
                ('rodzaj_parametrow4', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='produkty',
            name='rodzaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.paramrodz'),
        ),
    ]
