# Generated by Django 3.2.4 on 2021-06-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0007_auto_20210628_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='rodzaj',
        ),
        migrations.AddField(
            model_name='kategoria',
            name='rodzaj_parametrow1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kategoria',
            name='rodzaj_parametrow2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kategoria',
            name='rodzaj_parametrow3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kategoria',
            name='rodzaj_parametrow4',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ParamRodz',
        ),
    ]
