# Generated by Django 3.2.4 on 2021-06-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0008_auto_20210628_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wartosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc_parametrow1', models.TextField(blank=True)),
                ('wartosc_parametrow2', models.TextField(blank=True)),
                ('wartosc_parametrow3', models.TextField(blank=True)),
                ('wartosc_parametrow4', models.TextField(blank=True)),
                ('nazwa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.kategoria')),
            ],
            options={
                'verbose_name': 'Wartość parametru',
                'verbose_name_plural': 'Wartości parametrów',
            },
        ),
        migrations.AddField(
            model_name='produkty',
            name='wartosc_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.wartosc'),
        ),
    ]
