# Generated by Django 3.2.4 on 2021-06-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0009_auto_20210628_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='wartosc_param',
            new_name='wartosc',
        ),
    ]
