# Generated by Django 3.2.4 on 2021-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0010_rename_wartosc_param_produkty_wartosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wartosc',
            name='nazwa',
            field=models.CharField(max_length=40),
        ),
    ]
