# Generated by Django 3.2.4 on 2021-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0011_alter_wartosc_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdj',
            name='zdj_opis_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zdj',
            name='zdj_opis_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zdj',
            name='zdj_opis_3',
            field=models.TextField(blank=True),
        ),
    ]
